# For a quick start check out our HTTP Requests collection (Tools|HTTP Client|Open HTTP Requests Collection).
#
# Following HTTP Request Live Templates are available:
# * 'gtrp' and 'gtr' create a GET request with or without query parameters;
# * 'ptr' and 'ptrp' create a POST request with a simple or parameter-like body;
# * 'mptr' and 'fptr' create a POST request to submit a form with a text or file field (multipart/form-data);

GET http://localhost:8080/employee/delete?id=1
Accept: application/json

###

DELETE http://localhost:8080/employee

###

GET http://localhost:8080/api/employee

###

GET http://localhost:8080/api/employee?id=10001

###

GET http://localhost:8080/api2/employee/1

###

DELETE http://localhost:8080/api2/employee/2

###

POST http://localhost:8080/api2/employee
Content-Type: application/json

{
  "empNo": 2, "birthDate": "1999-12-01",
  "firstName": "Jonas", "lastName": "Jonaitis",
  "gender": "M",
  "hireDate": "2018-12-31"
}

###

PUT http://localhost:8080/api2/employee
Content-Type: application/json

{
  "empNo": 2, "birthDate": "1999-12-01",
  "firstName": "Ona", "lastName": "Onaite",
  "gender": "F",
  "hireDate": "2018-12-31"
}

###
### jurgis - be roles
### jonas - ADMIN
### petras - USER

POST http://localhost:8080/api2/login
Content-Type: application/x-www-form-urlencoded

username=jonas@firma.lt&password=123

###

GET http://localhost:8080/api2/login

###